---

- name: Provision VM on vSphere ESXi
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Create VM using datastore iso file
      community.vmware.vmware_deploy_ovf:
        esxi_hostname: "{{ esxi_ip }}"
        datacenter: "ha-datacenter" 
        deployment_option: standard

        ovf: "{{ ovf_path }}" 
        name: "{{ vm_name }}"
        datastore: "{{ datastore_name }}"
        networks:
          "NAT Network": "VM Network"
        power_on: yes        
      register: vm_info

    - name: Print VM information
      ansible.builtin.debug:
        var: vm_info       
